server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: microProveedores
          uri: lb://microProveedores
          predicates:
            - Path=/api/v1/proveedor/**, /api/v1/existencia/**, /api/v1/unidad/**
        - id: microStock
          uri: lb://microStock
          predicates:
            - Path=/api/v1/insumo/**, /api/v1/manufacturado/**, /api/v1/rubro/**
        - id: comanda-service
          uri: lb://comanda-service
          predicates:
            - Path=/microComanda/estados/**, /microComanda/comandas/**
        - id: microservicios-facturas
          uri: lb://microservicios-facturas
          predicates:
            - Path=/microFactura/estados/**, /microFactura/facturas/**
        - id: microservicio-pedidos
          uri: lb://microservicio-pedidos
          predicates:
            - Path=/microPedido/pedidos/**, /microPedido/pagos/**, /microPedido/estados/**
